### ISSUE TITLE
Issues with KeyError, AssertionError, and NameError during training with various configuration files

### ISSUE THREAD

**Issue by 1235357** [fengweie/SE_ASA#4]
Dear Wei Feng,

Thanks for your Work, I am currently using your codebase trying to reproduce your model performence and have encountered several issues while executing the `run_all_configs.sh` script located in the `scripts` directory. The problems are as follows:

1. **KeyError with 'CLASS_CENTER_FEA_INIT':** While running the configuration files `MPSCL_CT2MR.yml`, `MPSCL_MR2CT.yml`, `ours_CT2MR.yml`, and `ours_MR2CT.yml`, I encountered a `KeyError` stating that `'CLASS_CENTER_FEA_INIT is not a valid config key'`. It appears that the key `CLASS_CENTER_FEA_INIT` is not recognized within the configuration file. I am unsure if this key is supposed to be defined elsewhere or if there is a typo in the key name.

2. **AssertionError with missing initial model:** When running the configuration files `MT_CT2MR.yml` and `MT_MR2CT.yml`, I received an `AssertionError` indicating that the initial model could not be found. The paths provided in the error messages are `/home/zye/snapshots/CT2MR/senery_CT2MR/model_1500.pth` and `/home/zye/snapshots/MR2CT/AdvEnt_MR2CT/model_5000.pth` respectively. I have checked these paths and the specified files do not exist. I am unsure if these files were supposed to be provided or if they are generated during runtime.

3. **AssertionError with missing initial model (continued):** I encountered similar `AssertionError`s with the configuration files `senery_CT2MR.yml` and `senery_MR2CT.yml`. The paths provided in the error messages are `/home/zye/snapshots/CT2MR/AdvEnt_CT2MR/model_30000.pth` and `/home/zye/snapshots/MR2CT/AdvEnt_MR2CT/model_5000.pth` respectively. As with the previous issue, these files do not exist at the specified paths.

4. **NameError with undefined functions:** Lastly, while running the configuration files `warmup_CT2MR.yml` and `warmup_MR2CT.yml`, I received a `NameError` stating that the functions `train_advent` and `train_adaoutput` are not defined respectively. I have searched the codebase and could not find these functions defined anywhere.

I would greatly appreciate your assistance in resolving these issues. I am unsure if I am missing some files or if there are errors within the code. Please let me know if there are additional steps I need to take or if there are updates to the codebase that address these issues.

Thank you for your time and assistance.

Best regards!

---

My `run_all_configs.sh` script：

#!/bin/bash

#配置文件所在的目录
CONFIG_DIR="/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/configs"

#train.py 脚本的绝对路径
TRAIN_PY="/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py"

SCRIPTS_DIR="/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts"

#切换到配置文件目录
cd "$CONFIG_DIR"

#遍历配置目录下的所有 .yml 文件
for CONFIG_FILE in *.yml; do

    echo "Running training with configuration file: $CONFIG_FILE"

    # 运行 train.py 脚本，使用当前的配置文件，启用随机种子，开启TensorBoard，并设置每100次迭代可视化一次
    python "$TRAIN_PY" --cfg "$CONFIG_FILE" --random-train --tensorboard --viz-every-iter 100

done

# 脚本执行完成后，可以选择性地输出完成信息
echo "All configurations have been processed."

---

![image](https://github.com/fengweie/SE_ASA/assets/112318480/ed533e46-961c-4bd7-a8ab-6dfb9e8fe011)

![image](https://github.com/fengweie/SE_ASA/assets/112318480/a00f687a-7cfa-45b3-bf53-ae0993944ad7)

![image](https://github.com/fengweie/SE_ASA/assets/112318480/accb5131-ae05-4123-840a-34400066da54)

---

Complete terminal log:

(zye-SE_ASA-6_12) [zye@gpu01 scripts]$ ./run_all_configs.sh 
Running training with configuration file: baseline_CT2MR.yml
Called with args
Model loaded from:/home/zye/Desktop/2023_SpF/SE_ASA-main/pretrained_model/DeepLab_resnet_pretrained_imagenet.pth
dataloader finish
Running training with configuration file: baseline_MR2CT.yml
Called with args
Model loaded from:/home/zye/Desktop/2023_SpF/SE_ASA-main/pretrained_model/DeepLab_resnet_pretrained_imagenet.pth
dataloader finish
Running training with configuration file: MPSCL_CT2MR.yml
Called with args
Error under config key: TRAIN
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 50, in main
    cfg_from_file(args.cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 182, in cfg_from_file
    _merge_a_into_b(yaml_cfg, cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 170, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 156, in _merge_a_into_b
    raise KeyError(f'{k} is not a valid config key')
KeyError: 'CLASS_CENTER_FEA_INIT is not a valid config key'
Running training with configuration file: MPSCL_MR2CT.yml
Called with args
Error under config key: TRAIN
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 50, in main
    cfg_from_file(args.cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 182, in cfg_from_file
    _merge_a_into_b(yaml_cfg, cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 170, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 156, in _merge_a_into_b
    raise KeyError(f'{k} is not a valid config key')
KeyError: 'CLASS_CENTER_FEA_INIT is not a valid config key'
Running training with configuration file: MT_CT2MR.yml
Called with args
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 110, in main
    assert osp.exists(cfg.TRAIN.RESTORE_FROM), f'Missing init model {cfg.TRAIN.RESTORE_FROM}'
AssertionError: Missing init model /home/zye/snapshots/CT2MR/senery_CT2MR/model_1500.pth
Running training with configuration file: MT_MR2CT.yml
Called with args
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 110, in main
    assert osp.exists(cfg.TRAIN.RESTORE_FROM), f'Missing init model {cfg.TRAIN.RESTORE_FROM}'
AssertionError: Missing init model /home/zye/snapshots/MR2CT/AdvEnt_MR2CT/model_5000.pth
Running training with configuration file: ours_CT2MR.yml
Called with args
Error under config key: TRAIN
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 50, in main
    cfg_from_file(args.cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 182, in cfg_from_file
    _merge_a_into_b(yaml_cfg, cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 170, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 156, in _merge_a_into_b
    raise KeyError(f'{k} is not a valid config key')
KeyError: 'CLASS_CENTER_FEA_INIT is not a valid config key'
Running training with configuration file: ours_MR2CT.yml
Called with args
Error under config key: TRAIN
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 50, in main
    cfg_from_file(args.cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 182, in cfg_from_file
    _merge_a_into_b(yaml_cfg, cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 170, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/config.py", line 156, in _merge_a_into_b
    raise KeyError(f'{k} is not a valid config key')
KeyError: 'CLASS_CENTER_FEA_INIT is not a valid config key'
Running training with configuration file: senery_CT2MR.yml
Called with args
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 110, in main
    assert osp.exists(cfg.TRAIN.RESTORE_FROM), f'Missing init model {cfg.TRAIN.RESTORE_FROM}'
AssertionError: Missing init model /home/zye/snapshots/CT2MR/AdvEnt_CT2MR/model_30000.pth
Running training with configuration file: senery_MR2CT.yml
Called with args
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 110, in main
    assert osp.exists(cfg.TRAIN.RESTORE_FROM), f'Missing init model {cfg.TRAIN.RESTORE_FROM}'
AssertionError: Missing init model /home/zye/snapshots/MR2CT/AdvEnt_MR2CT/model_5000.pth
Running training with configuration file: warmup_CT2MR.yml
Called with args
Model loaded from:/home/zye/Desktop/2023_SpF/SE_ASA-main/pretrained_model/DeepLab_resnet_pretrained_imagenet.pth
dataloader finish
use method: AdvEnt
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 229, in main
    train_domain_adaptation(model,strain_loader,trgtrain_loader,sval_loader,cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/train_UDA.py", line 765, in train_domain_adaptation
    train_advent(model, strain_loader, sval_loader,trgtrain_loader, cfg)
NameError: name 'train_advent' is not defined
Running training with configuration file: warmup_MR2CT.yml
Called with args
Model loaded from:/home/zye/Desktop/2023_SpF/SE_ASA-main/pretrained_model/DeepLab_resnet_pretrained_imagenet.pth
dataloader finish
use method: Adaoutput
Traceback (most recent call last):
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 233, in <module>
    main()
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/scripts/train.py", line 229, in main
    train_domain_adaptation(model,strain_loader,trgtrain_loader,sval_loader,cfg)
  File "/home/zye/Desktop/2023_SpF/SE_ASA-main/domain_adaptation/train_UDA.py", line 768, in train_domain_adaptation
    train_adaoutput(model, strain_loader, sval_loader,trgtrain_loader, cfg)
NameError: name 'train_adaoutput' is not defined
All configurations have been processed.

**Comment by fengweie** [comment]
Thank you for your attention to our work.
      You need to pre-train the advent model first, then you can get the center features of each category.
As I mentioned, you need to warm up with the advent model first, then load the pre-trained weights here.
For the implementation of train_advent (https://github.com/valeoai/ADVENT) you can follow the original article. And train_adaoutput  simply replaces the input of the discriminator with the original output of the model.
